# Host: localhost  (Version: 5.5.5-10.1.8-MariaDB)
# Date: 2016-03-29 06:34:26
# Generator: MySQL-Front 5.3  (Build 4.113)

/*!40101 SET NAMES utf8 */;

#
# Structure for table "cosntitucion"
#

DROP TABLE IF EXISTS `cosntitucion`;
CREATE TABLE `cosntitucion` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `article` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

#
# Data for table "cosntitucion"
#

INSERT INTO `cosntitucion` VALUES (1,'Artículo 1','','<p>ARTICULO 1. EN LOS ESTADOS UNIDOS MEXICANOS TODAS LAS PERSONAS GOZARAN DE LOS DERECHOS HUMANOS RECONOCIDOS EN ESTA CONSTITUCION Y EN LOS TRATADOS INTERNACIONALES DE LOS QUE EL ESTADO MEXICANO SEA PARTE, ASI COMO DE LAS GARANTIAS PARA SU PROTECCION, CUY'),(2,'Artículo 2',NULL,'<p>ARTICULO 2. LA NACION MEXICANA ES UNICA E INDIVISIBLE.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>LA NACION TIENE UNA COMPOSICION PLURICULTURAL SUSTENTADA ORIGINALMENTE EN SUS PUEBLOS INDIGENAS QUE SON AQUELLOS QUE DESCIENDEN DE POBLACIONES QUE HABITABAN EN EL TERRITORIO ACTUAL DEL PAIS AL INICIARSE LA COLONIZACION Y QUE CONSERVAN SUS PROPIAS INSTITUCIONES SOCIALES, ECONOMICAS, CULTURALES Y POLITICAS, O PARTE DE ELLAS.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>LA CONCIENCIA DE SU IDENTIDAD INDIGENA DEBERA SER CRITERIO FUNDAMENTAL PARA DETERMINAR A QUIENES SE APLICAN LAS DISPOSICIONES SOBRE PUEBLOS INDIGENAS.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>SON COMUNIDADES INTEGRANTES DE UN PUEBLO INDIGENA, AQUELLAS QUE FORMEN UNA UNIDAD SOCIAL, ECONOMICA Y CULTURAL, ASENTADAS EN UN TERRITORIO Y QUE RECONOCEN AUTORIDADES PROPIAS DE ACUERDO CON SUS USOS Y COSTUMBRES.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>EL DERECHO DE LOS PUEBLOS INDIGENAS A LA LIBRE DETERMINACION SE EJERCERA EN UN MARCO CONSTITUCIONAL DE AUTONOMIA QUE ASEGURE LA UNIDAD NACIONAL. EL RECONOCIMIENTO DE LOS PUEBLOS Y COMUNIDADES INDIGENAS SE HARA EN LAS CONSTITUCIONES Y LEYES DE LAS ENTIDADES FEDERATIVAS, LAS QUE DEBERAN TOMAR EN CUENTA, ADEMAS DE LOS PRINCIPIOS GENERALES ESTABLECIDOS EN LOS PARRAFOS ANTERIORES DE ESTE ARTICULO, CRITERIOS ETNOLING&Uuml;ISTICOS Y DE ASENTAMIENTO FISICO.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>A. ESTA CONSTITUCION RECONOCE Y GARANTIZA EL DERECHO DE LOS PUEBLOS Y LAS COMUNIDADES INDIGENAS A LA LIBRE DETERMINACION Y, EN CONSECUENCIA, A LA AUTONOMIA PARA:  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>I. DECIDIR SUS FORMAS INTERNAS DE CONVIVENCIA Y ORGANIZACION SOCIAL, ECONOMICA, POLITICA Y CULTURAL.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>II. APLICAR SUS PROPIOS SISTEMAS NORMATIVOS EN LA REGULACION Y SOLUCION DE SUS CONFLICTOS INTERNOS, SUJETANDOSE A LOS PRINCIPIOS GENERALES DE ESTA CONSTITUCION, RESPETANDO LAS GARANTIAS INDIVIDUALES, LOS DERECHOS HUMANOS Y, DE MANERA RELEVANTE, LA DIGNIDAD E INTEGRIDAD DE LAS MUJERES. LA LEY ESTABLECERA LOS CASOS Y PROCEDIMIENTOS DE VALIDACION POR LOS JUECES O TRIBUNALES CORRESPONDIENTES.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>III. ELEGIR DE ACUERDO CON SUS NORMAS, PROCEDIMIENTOS Y PRACTICAS TRADICIONALES, A LAS AUTORIDADES O REPRESENTANTES PARA EL EJERCICIO DE SUS FORMAS PROPIAS DE GOBIERNO INTERNO, GARANTIZANDO QUE LAS MUJERES Y LOS HOMBRES INDIGENAS DISFRUTARAN Y EJERCERAN SU DERECHO DE VOTAR Y SER VOTADOS EN CONDICIONES DE IGUALDAD; ASI COMO A ACCEDER Y DESEMPE&Ntilde;AR LOS CARGOS PUBLICOS Y DE ELECCION POPULAR PARA LOS QUE HAYAN SIDO ELECTOS O DESIGNADOS, EN UN MARCO QUE RESPETE EL PACTO FEDERAL, LA SOBERANIA DE LOS ESTADOS Y LA AUTONOMIA DE LA CIUDAD DE MEXICO. EN NINGUN CASO LAS PRACTICAS COMUNITARIAS PODRAN LIMITAR LOS DERECHOS POLITICO-ELECTORALES DE LOS Y LAS CIUDADANAS EN LA ELECCION DE SUS AUTORIDADES MUNICIPALES.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 29 DE ENERO DE 2016)</p>\n\n<p>IV. PRESERVAR Y ENRIQUECER SUS LENGUAS, CONOCIMIENTOS Y TODOS LOS ELEMENTOS QUE CONSTITUYAN SU CULTURA E IDENTIDAD.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>V. CONSERVAR Y MEJORAR EL HABITAT Y PRESERVAR LA INTEGRIDAD DE SUS TIERRAS EN LOS TERMINOS ESTABLECIDOS EN ESTA CONSTITUCION.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>VI. ACCEDER, CON RESPETO A LAS FORMAS Y MODALIDADES DE PROPIEDAD Y TENENCIA DE LA TIERRA ESTABLECIDAS EN ESTA CONSTITUCION Y A LAS LEYES DE LA MATERIA, ASI COMO A LOS DERECHOS ADQUIRIDOS POR TERCEROS O POR INTEGRANTES DE LA COMUNIDAD, AL USO Y DISFRUTE PREFERENTE DE LOS RECURSOS NATURALES DE LOS LUGARES QUE HABITAN Y OCUPAN LAS COMUNIDADES, SALVO AQUELLOS QUE CORRESPONDEN A LAS AREAS ESTRATEGICAS, EN TERMINOS DE ESTA CONSTITUCION. PARA ESTOS EFECTOS LAS COMUNIDADES PODRAN ASOCIARSE EN TERMINOS DE LEY. (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>VII. ELEGIR, EN LOS MUNICIPIOS CON POBLACION INDIGENA, REPRESENTANTES ANTE LOS AYUNTAMIENTOS.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>LAS CONSTITUCIONES Y LEYES DE LAS ENTIDADES FEDERATIVAS RECONOCERAN Y REGULARAN ESTOS DERECHOS EN LOS MUNICIPIOS, CON EL PROPOSITO DE FORTALECER LA PARTICIPACION Y REPRESENTACION POLITICA DE CONFORMIDAD CON SUS TRADICIONES Y NORMAS INTERNAS.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>VIII. ACCEDER PLENAMENTE A LA JURISDICCION DEL ESTADO. PARA GARANTIZAR ESE DERECHO, EN TODOS LOS JUICIOS Y PROCEDIMIENTOS EN QUE SEAN PARTE, INDIVIDUAL O COLECTIVAMENTE, SE DEBERAN TOMAR EN CUENTA SUS COSTUMBRES Y ESPECIFICIDADES CULTURALES RESPETANDO LOS PRECEPTOS DE ESTA CONSTITUCION. LOS INDIGENAS TIENEN EN TODO TIEMPO EL DERECHO A SER ASISTIDOS POR INTERPRETES Y DEFENSORES QUE TENGAN CONOCIMIENTO DE SU LENGUA Y CULTURA.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>LAS CONSTITUCIONES Y LEYES DE LAS ENTIDADES FEDERATIVAS ESTABLECERAN LAS CARACTERISTICAS DE LIBRE DETERMINACION Y AUTONOMIA QUE MEJOR EXPRESEN LAS SITUACIONES Y ASPIRACIONES DE LOS PUEBLOS INDIGENAS EN CADA ENTIDAD, ASI COMO LAS NORMAS PARA EL RECONOCIMIENTO DE LAS COMUNIDADES INDIGENAS COMO ENTIDADES DE INTERES PUBLICO.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>B. LA FEDERACION, LAS ENTIDADES FEDERATIVAS Y LOS MUNICIPIOS, PARA PROMOVER LA IGUALDAD DE OPORTUNIDADES DE LOS INDIGENAS Y ELIMINAR CUALQUIER PRACTICA DISCRIMINATORIA, ESTABLECERAN LAS INSTITUCIONES Y DETERMINARAN LAS POLITICAS NECESARIAS PARA GARANTIZAR LA VIGENCIA DE LOS DERECHOS DE LOS INDIGENAS Y EL DESARROLLO INTEGRAL DE SUS PUEBLOS Y COMUNIDADES, LAS CUALES DEBERAN SER DISE&Ntilde;ADAS Y OPERADAS CONJUNTAMENTE CON ELLOS.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 29 DE ENERO DE 2016)  PARA ABATIR LAS CARENCIAS Y REZAGOS QUE AFECTAN A LOS PUEBLOS Y COMUNIDADES INDIGENAS, DICHAS AUTORIDADES, TIENEN LA OBLIGACION DE:  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>I. IMPULSAR EL DESARROLLO REGIONAL DE LAS ZONAS INDIGENAS CON EL PROPOSITO DE FORTALECER LAS ECONOMIAS LOCALES Y MEJORAR LAS CONDICIONES DE VIDA DE SUS PUEBLOS, MEDIANTE ACCIONES COORDINADAS ENTRE LOS TRES ORDENES DE GOBIERNO, CON LA PARTICIPACION DE LAS COMUNIDADES. LAS AUTORIDADES MUNICIPALES DETERMINARAN EQUITATIVAMENTE LAS ASIGNACIONES PRESUPUESTALES QUE LAS COMUNIDADES ADMINISTRARAN DIRECTAMENTE PARA FINES ESPECIFICOS.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>II. GARANTIZAR E INCREMENTAR LOS NIVELES DE ESCOLARIDAD, FAVORECIENDO LA EDUCACION BILING&Uuml;E E INTERCULTURAL, LA ALFABETIZACION, LA CONCLUSION DE LA EDUCACION BASICA, LA CAPACITACION PRODUCTIVA Y LA EDUCACION MEDIA SUPERIOR Y SUPERIOR. ESTABLECER UN SISTEMA DE BECAS PARA LOS ESTUDIANTES INDIGENAS EN TODOS LOS NIVELES. DEFINIR Y DESARROLLAR PROGRAMAS EDUCATIVOS DE CONTENIDO REGIONAL QUE RECONOZCAN LA HERENCIA CULTURAL DE SUS PUEBLOS, DE ACUERDO CON LAS LEYES DE LA MATERIA Y EN CONSULTA CON LAS COMUNIDADES INDIGENAS. IMPULSAR EL RESPETO Y CONOCIMIENTO DE LAS DIVERSAS CULTURAS EXISTENTES EN LA NACION.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>III. ASEGURAR EL ACCESO EFECTIVO A LOS SERVICIOS DE SALUD MEDIANTE LA AMPLIACION DE LA COBERTURA DEL SISTEMA NACIONAL, APROVECHANDO DEBIDAMENTE LA MEDICINA TRADICIONAL, ASI COMO APOYAR LA NUTRICION DE LOS INDIGENAS MEDIANTE PROGRAMAS DE ALIMENTACION, EN ESPECIAL PARA LA POBLACION INFANTIL.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>IV. MEJORAR LAS CONDICIONES DE LAS COMUNIDADES INDIGENAS Y DE SUS ESPACIOS PARA LA CONVIVENCIA Y RECREACION, MEDIANTE ACCIONES QUE FACILITEN EL ACCESO AL FINANCIAMIENTO PUBLICO Y PRIVADO PARA LA CONSTRUCCION Y MEJORAMIENTO DE VIVIENDA, ASI COMO AMPLIAR LA COBERTURA DE LOS SERVICIOS SOCIALES BASICOS.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>V. PROPICIAR LA INCORPORACION DE LAS MUJERES INDIGENAS AL DESARROLLO, MEDIANTE EL APOYO A LOS PROYECTOS PRODUCTIVOS, LA PROTECCION DE SU SALUD, EL OTORGAMIENTO DE ESTIMULOS PARA FAVORECER SU EDUCACION Y SU PARTICIPACION EN LA TOMA DE DECISIONES RELACIONADAS CON LA VIDA COMUNITARIA.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>VI. EXTENDER LA RED DE COMUNICACIONES QUE PERMITA LA INTEGRACION DE LAS COMUNIDADES, MEDIANTE LA CONSTRUCCION Y AMPLIACION DE VIAS DE COMUNICACION Y TELECOMUNICACION. ESTABLECER CONDICIONES PARA QUE LOS PUEBLOS Y LAS COMUNIDADES INDIGENAS PUEDAN ADQUIRIR, OPERAR Y ADMINISTRAR MEDIOS DE COMUNICACION, EN LOS TERMINOS QUE LAS LEYES DE LA MATERIA DETERMINEN.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>VII. APOYAR LAS ACTIVIDADES PRODUCTIVAS Y EL DESARROLLO SUSTENTABLE DE LAS COMUNIDADES INDIGENAS MEDIANTE ACCIONES QUE PERMITAN ALCANZAR LA SUFICIENCIA DE SUS INGRESOS ECONOMICOS, LA APLICACION DE ESTIMULOS PARA LAS INVERSIONES PUBLICAS Y PRIVADAS QUE PROPICIEN LA CREACION DE EMPLEOS, LA INCORPORACION DE TECNOLOGIAS PARA INCREMENTAR SU PROPIA CAPACIDAD PRODUCTIVA, ASI COMO PARA ASEGURAR EL ACCESO EQUITATIVO A LOS SISTEMAS DE ABASTO Y COMERCIALIZACION.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>VIII. ESTABLECER POLITICAS SOCIALES PARA PROTEGER A LOS MIGRANTES DE LOS PUEBLOS INDIGENAS, TANTO EN EL TERRITORIO NACIONAL COMO EN EL EXTRANJERO, MEDIANTE ACCIONES PARA GARANTIZAR LOS DERECHOS LABORALES DE LOS JORNALEROS AGRICOLAS; MEJORAR LAS CONDICIONES DE SALUD DE LAS MUJERES; APOYAR CON PROGRAMAS ESPECIALES DE EDUCACION Y NUTRICION A NI&Ntilde;OS Y JOVENES DE FAMILIAS MIGRANTES; VELAR POR EL RESPETO DE SUS DERECHOS HUMANOS Y PROMOVER LA DIFUSION DE SUS CULTURAS.  (REFORMADA MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>IX. CONSULTAR A LOS PUEBLOS INDIGENAS EN LA ELABORACION DEL PLAN NACIONAL DE DESARROLLO Y DE LOS PLANES DE LAS ENTIDADES FEDERATIVAS, DE LOS MUNICIPIOS Y, CUANDO PROCEDA, DE LAS DEMARCACIONES TERRITORIALES DE LA CIUDAD DE MEXICO Y, EN SU CASO, INCORPORAR LAS RECOMENDACIONES Y PROPUESTAS QUE REALICEN.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 29 DE ENERO DE 2016)</p>\n\n<p>PARA GARANTIZAR EL CUMPLIMIENTO DE LAS OBLIGACIONES SE&Ntilde;ALADAS EN ESTE APARTADO, LA CAMARA DE DIPUTADOS DEL CONGRESO DE LA UNION, LAS LEGISLATURAS DE LAS ENTIDADES FEDERATIVAS Y LOS AYUNTAMIENTOS, EN EL AMBITO DE SUS RESPECTIVAS COMPETENCIAS, ESTABLECERAN LAS PARTIDAS ESPECIFICAS DESTINADAS AL CUMPLIMIENTO DE ESTAS OBLIGACIONES EN LOS PRESUPUESTOS DE EGRESOS QUE APRUEBEN, ASI COMO LAS FORMAS Y PROCEDIMIENTOS PARA QUE LAS COMUNIDADES PARTICIPEN EN EL EJERCICIO Y VIGILANCIA DE LAS MISMAS.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>\n\n<p>SIN PERJUICIO DE LOS DERECHOS AQUI ESTABLECIDOS A FAVOR DE LOS INDIGENAS, SUS COMUNIDADES Y PUEBLOS, TODA COMUNIDAD EQUIPARABLE A AQUELLOS TENDRA EN LO CONDUCENTE LOS MISMOS DERECHOS TAL Y COMO LO ESTABLEZCA LA LEY.  (REFORMADO MEDIANTE DECRETO PUBLICADO EN EL DIARIO OFICIAL DE LA FEDERACION EL 14 DE AGOSTO DE 2001)</p>');

#
# Structure for table "questinarie"
#

DROP TABLE IF EXISTS `questinarie`;
CREATE TABLE `questinarie` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sex` varchar(255) DEFAULT NULL,
  `age` varchar(255) DEFAULT NULL,
  `school` varchar(255) DEFAULT NULL,
  `constitucion_opinion` varchar(255) DEFAULT NULL,
  `constitucion_level` varchar(255) DEFAULT NULL,
  `constitucion_frase` varchar(255) DEFAULT NULL,
  `constitucion_leer` varchar(255) DEFAULT NULL,
  `constitucion_leer_text` varchar(255) DEFAULT NULL,
  `constitucion_no_leer` varchar(255) DEFAULT NULL,
  `constitucion_describe` varchar(255) DEFAULT NULL,
  `constitucion_deacuerdo` varchar(255) DEFAULT NULL,
  `consideras` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Data for table "questinarie"
#

INSERT INTO `questinarie` VALUES (1,'f','$Questinarie','primaria','$Questinarie','mucho','he leido completa','conocer mis derechos','$Questinarie','no me resulta de interes','adecuada para la sociedad actual','valores adecuados','dejar la constitucion como esta','2016-03-29 05:50:59','2016-03-29 05:50:59'),(2,'f','registro','universidad','registro','mucho','he leido completa','conocer mis derechos','registro','no me resulta de interes','adecuada para la sociedad actual','valores adecuados','dejar la constitucion como esta','2016-03-29 06:00:47','2016-03-29 06:00:47');

#
# Structure for table "register"
#

DROP TABLE IF EXISTS `register`;
CREATE TABLE `register` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `ages` int(1) DEFAULT NULL,
  `study` varchar(255) DEFAULT NULL,
  `sex` varchar(55) DEFAULT NULL,
  `localite` varchar(255) DEFAULT NULL,
  `ocupation` int(11) DEFAULT NULL,
  `essay` varchar(55) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL,
  `questinarie` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

#
# Data for table "register"
#

INSERT INTO `register` VALUES (1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-03-29 05:45:46','2016-03-29 05:45:46',NULL),(2,NULL,NULL,NULL,NULL,'f',NULL,NULL,NULL,'2016-03-29 05:47:12','2016-03-29 05:47:12',NULL),(3,NULL,NULL,NULL,NULL,'f',NULL,NULL,NULL,'2016-03-29 05:49:35','2016-03-29 05:49:35',2),(4,'registro','fersaavedra85@hotmail.com',0,'registro','','',0,NULL,'2016-03-29 06:01:23','2016-03-29 06:01:23',2),(5,'registro','fersaavedra85@hotmail.com',0,'registro','','',0,NULL,'2016-03-29 06:04:26','2016-03-29 06:04:26',2);
